Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.network "public_network"

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get upgrade

     wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
     sudo dpkg -i packages-microsoft-prod.deb
     rm packages-microsoft-prod.deb

     sudo apt-get update && sudo apt-get install -y dotnet-sdk-6.0
     dotnet tool install --global --version 1.3.1 --add-source http://10.0.2.2:5555/v3/index.json --no-cache KPetrachyk
  SHELL
end