Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.network "public_network"
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get upgrade

     wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
     sudo dpkg -i packages-microsoft-prod.deb
     rm packages-microsoft-prod.deb

     sudo apt-get update && sudo apt-get install -y dotnet-sdk-6.0
     sudo apt-get install -y git
     
     git clone https://github.com/raccoon-hero/cross-platform-sketchbook.git
     cd cross-platform-sketchbook/page-5-auth0/Application
     dotnet run
  SHELL
end
